"""Série « Trouve l'erreur » : un défi chaque soir à 20 h, 14 numéros.

Même structure pour chaque numéro : accroche, plan fautif, indice, réponse entourée,
pourquoi, bon plan, lien avec CivRebar AI, appel à l'action. Les dessins sont dans defauts.py
(le n° 1 utilise le modèle « plan » de carrousels.py). Les règles sont énoncées comme des
principes : les valeurs réelles se calculent selon la norme et le projet.
"""


def trouve_erreur(n, key, sujet, indice, rep, rep_body, pq_title, pq_body, ok, ok_body, accroche, diagramme=False, plan=False):
    typ = "plan" if plan else "scn"

    def dessin(mode, tag, title, body):
        d = {"t": typ, "mode": mode, "tag": tag, "title": title, "body": body}
        if not plan:
            d["key"] = key
        return d

    if plan and diagramme:
        pourquoi = dessin("tranchant", "Pourquoi ?", pq_title, pq_body)
    elif diagramme:
        pourquoi = dessin("pourquoi", "Pourquoi ?", pq_title, pq_body)
    else:
        pourquoi = {"t": "text", "title": pq_title, "body": pq_body}
    return {
        "id": f"TE{n:02d}_{key}", "titre": f"Trouve l'erreur n° {n}", "objectif": "Défi du soir",
        "theme": "nuit" if n % 2 else "chaux", "kicker": f"Trouve l'erreur · n° {n}", "hashtags": ["#TrouveLErreur"],
        "slides": [
            {"t": "cover", "title": "Trouve **l'erreur** / sur ce plan.", "sub": f"{sujet} Un seul détail cloche. Réponds en commentaire avant de glisser."},
            dessin("erreur", "Le plan", "Tu as trouvé ?", "Écris ta réponse en commentaire, puis glisse."),
            {"t": "text", "title": "Un indice ?", "body": indice},
            dessin("reponse", "Réponse", rep, rep_body),
            pourquoi,
            dessin("correct", "Le bon plan", ok, ok_body),
            {"t": "text", "title": "Ce genre de détail, / CivRebar AI t'aidera / à le **repérer**.",
             "body": "Les vérifications font partie de notre feuille de route. Un nouveau défi chaque soir à 20 h."},
            {"t": "cta", "title": "Tu avais **trouvé** ?", "body": "Dis-le en commentaire, et abonne-toi pour le défi de demain.",
             "actions": ["Commente", "Partage", "Abonne-toi"]},
        ],
        "court": f"🔍 TROUVE L'ERREUR n° {n} : {accroche} Réponds en commentaire AVANT de glisser 👀",
        "legende": f"""🔍 TROUVE L'ERREUR — n° {n}

{sujet} Un seul détail cloche.

💬 Écris ta réponse en commentaire AVANT de regarder la solution 👀

Un nouveau défi chaque soir à 20 h. Abonne-toi pour ne pas le rater 🔩""",
    }


ERREURS = [
    trouve_erreur(1, "cadres", "Poutre sur deux appuis, charge répartie.",
                  "Demande-toi où l'**effort tranchant** est le plus fort sur cette poutre.",
                  "Les cadres sont serrés / au **mauvais endroit**.", "Espacés de 25 cm près des appuis, serrés à 10 cm au milieu : c'est l'inverse qu'il faut.",
                  "L'effort tranchant", "Sur une poutre sur deux appuis, il est **maximal aux appuis** et presque nul au milieu. Or ce sont les cadres qui le reprennent.",
                  "Serrés aux **appuis**, / plus espacés au milieu.", "Exemple de principe : les espacements réels se calculent selon les charges et la norme.",
                  "un seul détail cloche sur ce plan de poutre.", diagramme=True, plan=True),
    trouve_erreur(2, "barres_haut", "Poutre sur deux appuis, charge répartie.",
                  "Sur cette poutre, quelle face est **tendue** : le haut ou le bas ?",
                  "Les grosses barres / sont **en haut**.", "Les 3 HA20 sont en haut, les 2 HA14 en bas : c'est l'inverse qu'il faut.",
                  "Le moment fléchissant", "Sur deux appuis, la poutre fléchit vers le bas : c'est la **fibre inférieure** qui est tendue. Le béton ne résiste pas à la traction, l'acier si.",
                  "L'acier principal / **en bas**.", "Les barres les plus fortes là où le béton est tendu.",
                  "une poutre, deux appuis, un détail qui cloche.", diagramme=True),
    trouve_erreur(3, "console", "Console (balcon) encastrée dans un mur.",
                  "Une console plie vers le bas… quelle face **s'allonge** ?",
                  "L'acier principal / est **en bas**.", "Sur une console, c'est l'une des erreurs les plus dangereuses : le balcon peut s'effondrer.",
                  "La console travaille / à l'envers", "Encastrée dans le mur, elle est tendue **en haut**. L'acier principal doit y être, bien ancré dans le mur.",
                  "Acier principal **en haut**, / ancré dans le mur.", "Les barres du dessous servent surtout au montage.",
                  "ce balcon cache une erreur dangereuse.", diagramme=True),
    trouve_erreur(4, "enrobage", "Coupe d'une poutre, juste avant le bétonnage.",
                  "Regarde la distance entre l'acier et la **surface** du béton.",
                  "Les barres touchent / le **coffrage**.", "Enrobage nul : l'acier sera à nu dès le décoffrage.",
                  "Pourquoi c'est grave", "Sans béton autour, l'acier rouille, gonfle et fait éclater le béton. En cas d'incendie, il chauffe trop vite. L'enrobage minimal dépend de l'exposition : voir la norme.",
                  "Un **enrobage** / tout autour.", "Des cales entre l'acier et le coffrage garantissent l'enrobage prévu au plan.",
                  "une coupe de poutre, un détail invisible après coulage."),
    trouve_erreur(5, "crochets", "Coupe d'une poutre : un cadre et ses barres.",
                  "Regarde bien le **coin en haut à gauche** du cadre.",
                  "Le cadre / est **ouvert**.", "Ses extrémités s'arrêtent sans crochet : il peut s'ouvrir sous l'effort.",
                  "Un cadre doit rester fermé", "Les crochets à **135°** replient les extrémités vers le cœur du béton : le cadre reste fermé et tient les barres, même en cas de séisme.",
                  "Fermé par des / crochets à **135°**.", "Le détail que seuls les gens du métier remarquent.",
                  "regarde bien ce cadre."),
    trouve_erreur(6, "recouvrement", "Deux barres HA16 raboutées dans une poutre.",
                  "Pour que l'effort passe d'une barre à l'autre, il faut de la **longueur**.",
                  "Le recouvrement / est **trop court**.", "10 cm de chevauchement : la barre peut glisser, l'effort ne passe pas.",
                  "Comment l'effort passe", "Par adhérence au béton, sur toute la longueur de chevauchement. On compte en général **40 à 50 fois le diamètre**, selon le béton, l'acier et la norme.",
                  "Un recouvrement / d'environ **50 Ø**.", "Pour un HA16 : de l'ordre de 65 à 80 cm.",
                  "deux barres, un raccord qui ne tiendra pas."),
    trouve_erreur(7, "attentes", "Un poteau qui doit continuer à l'étage au-dessus.",
                  "Comment le poteau de l'étage supérieur va-t-il se **raccorder** ?",
                  "Il n'y a pas / d'**attentes**.", "Les barres s'arrêtent au niveau du plancher : le poteau du dessus ne sera pas relié.",
                  "À quoi servent les attentes", "Ce sont les barres qui dépassent, en attente du niveau suivant. Elles assurent la **continuité** : sans elles, le poteau supérieur est simplement posé.",
                  "Des attentes sur une / longueur de **recouvrement**.", "Elles se chevauchent avec les barres du poteau supérieur.",
                  "ce poteau va poser problème à l'étage."),
    trouve_erreur(8, "semelle", "Semelle isolée sous un poteau.",
                  "Le sol pousse sous la semelle : quelle face est **tendue** ?",
                  "La nappe / est **en haut**.", "Placée en partie haute, elle ne sert presque à rien.",
                  "La semelle fléchit", "Le poteau appuie au centre, le sol repousse partout : la semelle se cintre et son **bas est tendu**.",
                  "La nappe **en bas**, / sur cales.", "Avec l'enrobage prévu, sur un béton de propreté.",
                  "une fondation, une nappe mal placée.", diagramme=True),
    trouve_erreur(9, "dalle", "Dalle portant entre deux murs, vue de dessus.",
                  "Les grosses barres doivent suivre le chemin des charges vers les **appuis**.",
                  "Les barres principales / sont dans le **mauvais sens**.", "Elles sont parallèles aux murs : elles ne portent rien jusqu'aux appuis.",
                  "Le sens de la portée", "Une dalle qui porte entre deux murs fléchit dans le sens de la portée. Les barres principales vont **d'un mur à l'autre** ; les barres de répartition sont perpendiculaires.",
                  "Principales / **d'un mur à l'autre**.", "Les barres fines, perpendiculaires, répartissent les charges.",
                  "cette dalle est armée… dans le bon sens ?"),
    trouve_erreur(10, "serrees", "Coupe d'une poutre fortement armée.",
                  "Imagine le béton et ses graviers qui doivent **couler** entre ces barres.",
                  "Les barres sont / **trop serrées**.", "Six HA25 collées : le béton ne passe pas, il restera des vides.",
                  "Laisser passer le béton", "Entre deux barres, il faut au moins **le diamètre de la barre**, et assez d'espace pour le plus gros granulat. Sinon : nids de cailloux et acier mal enrobé.",
                  "**Deux lits**, / bien espacés.", "Même section d'acier, mais le béton peut enrober chaque barre.",
                  "beaucoup d'acier… trop serré ?"),
    trouve_erreur(11, "chapeaux", "Poutre continue sur trois appuis.",
                  "Au-dessus de l'appui du milieu, la poutre se plie dans l'**autre sens**.",
                  "Il manque / les **chapeaux**.", "Au-dessus de l'appui intermédiaire, il n'y a qu'une fine barre de montage.",
                  "Le moment sur appui", "Sur une poutre continue, le moment devient **négatif** sur l'appui intermédiaire : c'est le haut qui est tendu, il faut de l'acier en haut.",
                  "Des **chapeaux** / sur l'appui.", "Des barres supérieures prolongées de part et d'autre de l'appui.",
                  "trois appuis, un oubli classique.", diagramme=True),
    trouve_erreur(12, "escalier", "Paillasse et palier d'un escalier, en coupe.",
                  "Regarde la barre du dessous au **changement de pente**.",
                  "La barre suit / l'**angle rentrant**.", "Tendue, elle va vouloir se redresser et faire sauter le béton sous l'angle.",
                  "L'effet « poussée au vide »", "Une barre tendue qui suit un angle rentrant pousse vers l'extérieur et fait éclater l'enrobage. Il faut **croiser** les barres et ancrer chacune au-delà de l'angle.",
                  "Des barres **croisées** / et ancrées.", "Chaque barre continue droit et s'ancre dans l'autre partie.",
                  "un escalier, un angle piège."),
    trouve_erreur(13, "ancrage", "Extrémité d'une poutre sur son appui de rive.",
                  "Regarde où s'**arrête** la barre du dessous.",
                  "La barre n'est / pas **ancrée**.", "Elle s'arrête au nu de l'appui : elle ne peut pas transmettre son effort.",
                  "Ancrer, c'est accrocher", "Une barre tendue doit se prolonger dans l'appui sur sa **longueur d'ancrage**, droite ou avec crochet, pour que l'effort passe au béton.",
                  "Prolongée dans l'appui, / avec **crochet**.", "La longueur d'ancrage se calcule selon le diamètre et le béton.",
                  "la fin de cette poutre ne tiendra pas."),
    trouve_erreur(14, "semelle_sol", "Semelle isolée, nappe en place avant le coulage.",
                  "Qu'y a-t-il entre l'acier et la **terre** ?",
                  "La nappe est posée / **à même le sol**.", "Pas de béton de propreté, pas de cales : l'acier touche la terre.",
                  "Protéger l'acier", "Au contact de la terre humide, l'acier rouille. On coule d'abord un **béton de propreté**, puis on pose la nappe sur des cales pour garantir l'enrobage.",
                  "Béton de propreté / + **cales**.", "L'enrobage est assuré sur toute la surface.",
                  "une erreur qu'on voit sur beaucoup de chantiers."),
]


def trouve_erreur_fiche(n, sujet, entete, champs, i_faux, bon, indice, rep, rep_body,
                        pq_title, pq_body, ok_body, accroche):
    """Variante « lis la fiche » : l'erreur est une valeur du tableau, pas un trait du dessin."""
    faux = list(champs)
    corrige = [(k, bon if j == i_faux else v) for j, (k, v) in enumerate(faux)]
    cle, val = faux[i_faux]
    return {
        "id": f"TE{n:02d}_fiche", "titre": f"Trouve l'erreur n° {n}", "objectif": "Défi du soir",
        "theme": "nuit" if n % 2 else "chaux", "kicker": f"Trouve l'erreur · n° {n}", "hashtags": ["#TrouveLErreur"],
        "slides": [
            {"t": "cover", "title": "Trouve **l'erreur** / sur cette fiche.", "sub": f"{sujet} Une valeur ne va pas. Réponds en commentaire avant de glisser."},
            {"t": "fields", "ph": entete, "title": "Tu as trouvé ?", "fields": faux,
             "body": "Écris ta réponse en commentaire, puis glisse."},
            {"t": "text", "title": "Un indice ?", "body": indice},
            {"t": "fields", "ph": entete, "title": rep, "fields": faux, "bad": i_faux, "body": rep_body},
            {"t": "text", "title": pq_title, "body": pq_body},
            {"t": "fields", "ph": entete, "title": "La fiche **corrigée**.", "fields": corrige, "body": ok_body},
            {"t": "text", "title": "Ce genre de valeur, / CivRebar AI t'aidera / à la **contrôler**.",
             "body": "Les vérifications font partie de notre feuille de route. Un nouveau défi chaque soir à 20 h."},
            {"t": "cta", "title": "Tu avais **trouvé** ?", "body": "Dis-le en commentaire, et abonne-toi pour le défi de demain.",
             "actions": ["Commente", "Partage", "Abonne-toi"]},
        ],
        "court": f"🔍 TROUVE L'ERREUR n° {n} : {accroche} Réponds en commentaire AVANT de glisser 👀",
        "legende": f"""🔍 TROUVE L'ERREUR — n° {n}

{sujet} Une valeur ne va pas.

💬 Écris ta réponse en commentaire AVANT de regarder la solution 👀

Un nouveau défi chaque soir à 20 h. Abonne-toi pour ne pas le rater 🔩""",
    }


# ---------------------------------------------------------------- numéros 15 à 43 (13/10 → 10/11)
ERREURS += [
    trouve_erreur(15, "poteau_cadres", "Poteau d'un bâtiment courant, vu en élévation.",
                  "Sur un poteau, tous les niveaux travaillent-ils de la même façon ? Regarde la **tête** et le **pied**.",
                  "Les cadres sont espacés / **pareil partout**.", "Même espacement du pied à la tête : les extrémités ne sont pas renforcées.",
                  "Les zones critiques", "En pied et en tête de poteau, les efforts se concentrent. On y **resserre les cadres** pour confiner le béton et empêcher les barres de flamber.",
                  "Cadres **resserrés** / aux extrémités.", "Exemple de principe : les longueurs et espacements réels se calculent selon la norme et le projet.",
                  "un poteau, un détail que beaucoup oublient."),
    trouve_erreur(16, "poteau_enrobage", "Coupe d'un poteau, juste avant le coulage.",
                  "Mesure la distance entre les barres et la **face extérieure**.",
                  "Les barres touchent / le **coffrage**.", "Enrobage quasi nul : l'acier sera à fleur de béton.",
                  "Un poteau est exposé", "Pluie, humidité, pollution : sans béton autour, l'acier rouille et fait **éclater** les angles. L'enrobage dépend de l'exposition et de la durée de vie visée.",
                  "Un **enrobage** / sur les quatre faces.", "Des cales sur chaque face garantissent la distance prévue au plan.",
                  "une coupe de poteau, un détail invisible après coulage."),
    trouve_erreur(17, "noeud", "Jonction entre une poutre et un poteau.",
                  "Regarde ce qui se passe **à l'intérieur** du croisement.",
                  "Aucun cadre / dans le **nœud**.", "Les cadres du poteau s'arrêtent avant le nœud et reprennent après.",
                  "Le nœud encaisse tout", "C'est là que les efforts de la poutre passent dans le poteau. Sans cadres, le béton du nœud n'est pas **confiné** : c'est un point de rupture classique en cas de séisme.",
                  "Des cadres **traversent** / le nœud.", "On prolonge les cadres du poteau à travers toute la hauteur de la poutre.",
                  "une jonction poutre-poteau, un oubli fréquent."),
    trouve_erreur(18, "poteau_recouv", "Poteau et reprise des barres au niveau d'un plancher.",
                  "Où le poteau est-il le plus **sollicité** : en pied ou à mi-hauteur ?",
                  "Le recouvrement est / **en pied de poteau**.", "Les barres se chevauchent juste au-dessus du plancher, dans la zone la plus chargée.",
                  "Éviter la zone critique", "Un recouvrement est un point faible : deux barres qui se transmettent l'effort par le béton. On le place donc **loin des extrémités**, de préférence vers le milieu.",
                  "Recouvrement / **à mi-hauteur**.", "Exemple de principe : la position et la longueur se définissent selon la norme et le projet.",
                  "un poteau, un recouvrement mal placé."),
    trouve_erreur(19, "voile", "Voile en béton armé, vu en coupe horizontale.",
                  "Compte le nombre de **nappes** d'armatures dans l'épaisseur.",
                  "Il n'y a qu'**une seule** / nappe.", "Toutes les barres sont d'un seul côté de l'épaisseur.",
                  "Un voile travaille des deux côtés", "Le vent, le séisme ou la poussée peuvent venir d'un côté **ou de l'autre**. Il faut donc une nappe sur chaque face, reliées par des épingles.",
                  "Deux nappes, / reliées par des **épingles**.", "Les épingles empêchent les nappes de s'écarter pendant le coulage.",
                  "un voile, une nappe qui manque."),
    trouve_erreur(20, "tremie", "Dalle avec une réservation pour un passage de gaines.",
                  "Les barres coupées par la trémie, où vont-elles **reprendre** leur effort ?",
                  "La trémie n'a / **aucun renfort**.", "Le treillis est simplement interrompu autour du percement.",
                  "Une trémie coupe le cheminement", "Les barres coupées ne portent plus rien. Il faut les **remplacer** : des barres de chevêtre sur les quatre côtés, et des barres en diagonale aux angles.",
                  "Chevêtre + barres / **en diagonale**.", "Les angles d'une trémie sont des points de départ de fissures.",
                  "une dalle percée, un renfort oublié."),
    trouve_erreur(21, "linteau", "Linteau au-dessus d'une ouverture, posé sur la maçonnerie.",
                  "Regarde de combien le linteau **repose** de chaque côté.",
                  "L'appui est / **trop court**.", "Le linteau mord à peine sur la maçonnerie à droite.",
                  "Tout passe par l'appui", "La charge du linteau se concentre sur sa portée d'appui. Trop court, le béton **poinçonne** la maçonnerie, et les barres n'ont pas la place d'être ancrées.",
                  "Un appui **suffisant** / de chaque côté.", "Exemple de principe : la longueur d'appui se définit selon la portée, la charge et le support.",
                  "un linteau, un appui qui pose question."),
    trouve_erreur(22, "longrine", "Longrine de fondation passant sur un poteau.",
                  "Suis une barre du regard, de gauche à droite : **s'arrête-t-elle** ?",
                  "L'acier est interrompu / **sur l'appui**.", "Les barres s'arrêtent de part et d'autre du poteau.",
                  "L'appui est le point le plus sollicité", "Sur un appui intermédiaire, la longrine est tendue **en partie haute**. Couper l'acier juste là, c'est couper exactement ce qui porte.",
                  "Acier **continu** / et renfort sur l'appui.", "On prolonge les barres et on ajoute un renfort au droit de l'appui.",
                  "une longrine, une coupure au mauvais endroit."),
    trouve_erreur(23, "radier", "Radier général sous un poteau. Le sol pousse vers le haut.",
                  "Si le sol pousse **vers le haut**, quelle face du radier est tendue sous le poteau ?",
                  "La nappe principale / est **en bas**.", "Les grosses barres sont en partie basse, sous le poteau.",
                  "Un radier travaille à l'envers", "Les charges descendent par les poteaux, le sol réagit **vers le haut** : sous un poteau, c'est la fibre supérieure qui est tendue. Les aciers principaux y vont.",
                  "Nappe principale / **en partie haute**.", "Un radier se ferraille comme une dalle retournée.",
                  "un radier, un sens de travail souvent inversé.", diagramme=False),
    trouve_erreur(24, "souten", "Mur de soutènement retenant un remblai.",
                  "La terre pousse le mur. Quelle face du voile **s'allonge** ?",
                  "L'acier est du / **mauvais côté**.", "Les barres principales sont côté terre, là où le béton est comprimé.",
                  "Le mur fléchit vers l'avant", "Poussé par le remblai, le voile se courbe : la face **opposée à la terre** est tendue. C'est là que doit se trouver l'acier principal.",
                  "Acier principal côté / **opposé à la terre**.", "La même logique que pour une console, mais à la verticale.",
                  "un mur de soutènement, un acier mal placé."),
    trouve_erreur(25, "poteau_court", "Poteau partiellement bridé par deux allèges maçonnées.",
                  "Sur quelle **hauteur** ce poteau peut-il réellement se déformer ?",
                  "Les cadres ne sont pas / **resserrés**.", "Le poteau est ferraillé comme un poteau normal, alors qu'il n'est libre que sur une courte hauteur.",
                  "L'effet « poteau court »", "Bridé par les allèges, le poteau ne peut fléchir que sur une faible hauteur : l'effort tranchant y devient **très élevé**. C'est une cause classique de rupture en cisaillement.",
                  "Cadres **très resserrés** / sur la partie libre.", "Autre solution : désolidariser l'allège du poteau par un joint.",
                  "un poteau coincé entre deux allèges.", diagramme=False),
    trouve_erreur(26, "reprise", "Arrêt de bétonnage : le coulage reprendra demain.",
                  "Comment le béton de demain va-t-il **tenir** sur celui d'aujourd'hui ?",
                  "La surface est **lisse**, / sans attentes.", "Rien ne dépasse, et la surface a été talochée.",
                  "Une reprise, c'est un point faible", "Deux bétons coulés à des moments différents n'adhèrent pas tout seuls. Il faut une surface **rugueuse** et des armatures qui traversent le joint.",
                  "Surface **rugueuse** / et attentes en place.", "On repique, on nettoie, on humidifie, et on laisse les attentes dépasser.",
                  "un arrêt de bétonnage, une préparation oubliée."),
    trouve_erreur(27, "epingles", "Coupe d'une poutre large, avec plusieurs barres en nappe basse.",
                  "Les barres du **milieu** sont-elles tenues par quelque chose ?",
                  "Les barres centrales / ne sont **pas tenues**.", "Seul le cadre extérieur maintient les barres d'angle.",
                  "Un cadre ne tient que ses angles", "Les barres situées entre les angles peuvent **flamber** vers l'extérieur sous compression. Des épingles viennent les relier au cadre.",
                  "Des **épingles** sur les / barres intermédiaires.", "Règle d'atelier : une barre sur deux au moins doit être tenue.",
                  "une poutre large, des barres livrées à elles-mêmes."),
    trouve_erreur(28, "treillis", "Deux panneaux de treillis soudé posés côte à côte sur une dalle.",
                  "Regarde la zone où les deux panneaux **se superposent**.",
                  "Le recouvrement est / **trop court**.", "Les panneaux se touchent à peine : une maille de chevauchement au plus.",
                  "Les panneaux doivent se relayer", "Un treillis transmet l'effort d'un panneau à l'autre par **adhérence**. Si le chevauchement est insuffisant, la dalle se comporte comme si elle était coupée à cet endroit.",
                  "Un recouvrement / **suffisant**.", "Exemple de principe : la longueur se définit selon le treillis et la norme.",
                  "deux panneaux de treillis, un chevauchement douteux."),
    trouve_erreur(29, "porte_faux", "Dalle avec un porte-à-faux prolongeant une travée.",
                  "Les chapeaux du porte-à-faux : **jusqu'où** doivent-ils aller dans la travée ?",
                  "Les chapeaux / s'arrêtent **trop tôt**.", "Les barres supérieures ne rentrent presque pas dans la travée voisine.",
                  "Un porte-à-faux tire vers le haut", "Il est tendu **en partie supérieure** sur tout son appui, et cette traction doit être ancrée loin dans la travée. Un chapeau trop court, et la dalle casse net à l'appui.",
                  "Chapeaux **prolongés** / dans la travée.", "Exemple de principe : la longueur se calcule selon la portée en console et les charges.",
                  "un balcon, des chapeaux un peu courts."),
    trouve_erreur(30, "sens_dalle", "Dalle rectangulaire portant sur deux appuis seulement.",
                  "Dans quel sens cette dalle **porte**-t-elle réellement ?",
                  "Les grosses barres sont / dans le **mauvais sens**.", "Les barres les plus fortes vont d'un appui à l'autre… dans la mauvaise direction.",
                  "Le sens de portée", "Une dalle sur deux appuis porte dans le sens de la **petite portée**, perpendiculairement aux appuis. C'est dans ce sens que vont les aciers principaux ; les autres ne sont que de la répartition.",
                  "Aciers principaux dans / le sens de la **portée**.", "Erreur courante quand le plan est tourné d'un quart de tour.",
                  "une dalle, un sens de portée inversé."),
    trouve_erreur(31, "pliage", "Barre pliée en atelier, en attente de pose.",
                  "Regarde l'**angle** : comment la barre a-t-elle été pliée ?",
                  "Le pliage est / **trop serré**.", "L'angle est quasiment vif, sans rayon.",
                  "Plier, ce n'est pas casser", "Un pliage trop serré **fissure** le béton à l'intérieur de l'angle et fragilise l'acier lui-même. Chaque diamètre a un rayon de pliage minimal.",
                  "Un **rayon de pliage** / respecté.", "Exemple de principe : le rayon dépend du diamètre et de la nuance d'acier.",
                  "une barre pliée, un angle qui interroge."),
    trouve_erreur(32, "about", "Extrémité d'une poutre posée sur son appui de rive.",
                  "La barre inférieure s'arrête sur l'appui : est-ce qu'elle y est **retenue** ?",
                  "La barre s'arrête / **net** sur l'appui.", "Aucun retour, aucun crochet en bout de barre.",
                  "Une barre doit être ancrée", "Sur un appui de rive, la barre inférieure arrive encore tendue. Sans **ancrage**, elle glisse dans le béton et la poutre se fissure à l'about.",
                  "Un **retour d'about** / en bout de barre.", "Un retour vertical ou un crochet suffit généralement.",
                  "une extrémité de poutre, un ancrage absent."),
    trouve_erreur(33, "cale_dalle", "Dalle ferraillée, juste avant le coulage.",
                  "Sur quoi les aciers **reposent**-ils ?",
                  "Les aciers sont posés / sur le **coffrage**.", "La nappe est directement à plat sur le fond de moule.",
                  "Sans cales, pas d'enrobage", "Les aciers doivent être **maintenus en l'air** à la hauteur prévue. Posés au fond, ils se retrouvent à nu sous la dalle, et la dalle perd sa hauteur utile.",
                  "Des **cales** sous / les aciers.", "Les cales se posent avant le ferraillage, à une densité suffisante.",
                  "une dalle prête à couler, un détail au sol."),
    trouve_erreur(34, "nappe_semelle", "Semelle isolée sous un poteau, coupe verticale.",
                  "À quelle hauteur se trouve la nappe d'armatures dans la semelle ?",
                  "La nappe est / **trop haute**.", "Les barres sont vers le milieu de l'épaisseur, loin du fond.",
                  "La semelle fléchit vers le haut", "Le sol pousse par-dessous : la face **inférieure** de la semelle est tendue. La nappe doit donc être en partie basse, avec juste l'enrobage nécessaire.",
                  "Nappe **en partie basse**, / barres relevées en bout.", "Les retours en extrémité assurent l'ancrage des barres.",
                  "une semelle, une nappe mal positionnée."),

    # ---- lecture de fiche : l'erreur est dans les valeurs, pas dans le trait
    trouve_erreur_fiche(35, "Poutre de rive d'un bâtiment, exposée à la pluie.", "PLAN BA-12 · POUTRE P3",
                        [("Section", "30 × 60 cm"), ("Portée", "5,40 m"), ("Exposition", "Extérieur, sous la pluie"),
                         ("Enrobage", "1,0 cm"), ("Armatures", "3 HA20 / 2 HA14")], 3, "selon la norme (ext.)",
                        "Compare la ligne « exposition » et la ligne juste en dessous.",
                        "Un **enrobage** de 1 cm / en extérieur.", "Pour une pièce exposée à la pluie, c'est bien trop faible.",
                        "L'enrobage dépend du milieu", "À l'abri, on peut descendre bas. Dehors, en bord de mer ou en milieu agressif, il faut **beaucoup plus** de béton autour de l'acier, sinon il rouille.",
                        "La valeur se détermine selon la classe d'exposition et la durée de vie visée.",
                        "une poutre de rive, une valeur qui ne colle pas."),
    trouve_erreur_fiche(36, "Poutre courante d'un plancher d'habitation.", "PLAN BA-07 · POUTRE P12",
                        [("Section", "25 × 50 cm"), ("Portée", "4,80 m"), ("Cadres", "HA8"),
                         ("Espacement", "40 cm partout"), ("Armatures", "3 HA16 / 2 HA12")], 3, "≤ 0,9 d, resserré aux appuis",
                        "Un cadre ne sert que s'il **croise** la fissure d'effort tranchant.",
                        "Des cadres tous les / **40 cm**.", "Et la même valeur du début à la fin de la poutre.",
                        "Deux problèmes d'un coup", "Un espacement trop grand laisse passer la fissure **entre deux cadres**. Et un espacement constant ignore que l'effort tranchant est maximal aux appuis.",
                        "L'espacement se calcule par zone, avec un maximum imposé par la norme.",
                        "une fiche de poutre, un espacement surprenant."),
    trouve_erreur_fiche(37, "Reprise de barres dans un poteau.", "PLAN BA-03 · POTEAU C4",
                        [("Section", "30 × 30 cm"), ("Barres", "4 HA16"), ("Nuance", "B500"),
                         ("Recouvrement", "10 Ø"), ("Position", "Mi-hauteur")], 3, "selon la norme (≈ 50 Ø)",
                        "Deux barres bout à bout ne se touchent pas : c'est le **béton** qui transmet l'effort.",
                        "Un recouvrement / de **10 Ø**.", "Soit 16 cm pour des HA16 : bien trop court.",
                        "Le recouvrement est une longueur d'adhérence", "L'effort passe d'une barre à l'autre par **frottement** sur toute la longueur de chevauchement. Trop court, les barres glissent.",
                        "La longueur dépend du diamètre, de la nuance, du béton et de la position des barres.",
                        "une reprise de poteau, une longueur douteuse."),
    trouve_erreur_fiche(38, "Poutre d'un plancher courant.", "PLAN BA-21 · POUTRE P8",
                        [("Section", "25 × 55 cm"), ("Portée", "5,00 m"), ("Armatures basses", "3 Ø20 lisses"),
                         ("Cadres", "HA8"), ("Béton", "C25/30")], 2, "3 HA20",
                        "Regarde le type de barre utilisé en **partie basse**.",
                        "Des ronds **lisses** / en acier principal.", "La ligne indique des barres lisses, pas des barres à haute adhérence.",
                        "L'adhérence fait tout", "Les nervures d'une barre HA lui permettent de **s'accrocher** au béton. Une barre lisse glisse : on ne l'utilise plus comme armature principale.",
                        "Les armatures principales sont en acier à haute adhérence.",
                        "une fiche de poutre, un type d'acier inattendu."),
    trouve_erreur_fiche(39, "Poutre reprenant un plancher d'habitation.", "PLAN BA-15 · POUTRE P2",
                        [("Section", "20 × 20 cm"), ("Portée", "6,00 m"), ("Charge", "Plancher courant"),
                         ("Armatures", "2 HA12 / 2 HA10"), ("Béton", "C25/30")], 0, "à redimensionner",
                        "Compare la **hauteur** de la poutre et sa **portée**.",
                        "Une poutre de 20 cm / sur **6 mètres**.", "La hauteur est dérisoire par rapport à la portée.",
                        "La hauteur fait la raideur", "Une poutre résiste surtout par sa **hauteur**. Trop plate, elle fléchit et vibre, même si les aciers « passent » au calcul. On vise en général une hauteur de l'ordre du dixième de la portée.",
                        "Avant de ferrailler, on redimensionne la section.",
                        "une poutre très longue, une section très fine."),
    trouve_erreur_fiche(40, "Poutre étroite dans un mur de refend.", "PLAN BA-09 · POUTRE P5",
                        [("Largeur", "15 cm"), ("Hauteur", "50 cm"), ("Armatures basses", "4 HA25"),
                         ("Cadres", "HA8"), ("Enrobage", "3 cm")], 2, "à répartir sur deux lits",
                        "Pose les barres côte à côte dans la largeur et **compte** la place.",
                        "4 HA25 dans / **15 cm** de large.", "Avec l'enrobage et les cadres, elles ne rentrent pas côte à côte.",
                        "Le béton doit passer entre les barres", "Il faut un **espace libre** entre deux barres pour que le béton et ses granulats descendent. Sinon : nids de cailloux, et l'acier n'est plus enrobé.",
                        "On répartit les barres sur deux lits, ou on élargit la poutre.",
                        "une poutre étroite, des barres trop nombreuses."),
    trouve_erreur_fiche(41, "Poteau d'angle d'un petit bâtiment.", "PLAN BA-05 · POTEAU A1",
                        [("Section", "25 × 25 cm"), ("Barres", "4 HA8"), ("Cadres", "HA12"),
                         ("Espacement", "15 cm"), ("Nuance", "B500")], 1, "4 HA12 minimum",
                        "Compare le diamètre des **barres verticales** et celui des **cadres**.",
                        "Les cadres sont plus gros / que les **barres**.", "HA12 pour les cadres, HA8 pour les armatures principales : c'est inversé.",
                        "Chacun son rôle", "Les barres verticales reprennent la **compression** : ce sont les plus fortes. Les cadres ne font que les tenir. Un poteau a aussi un diamètre minimal de barre imposé.",
                        "On remonte le diamètre des barres principales et on garde des cadres plus fins.",
                        "un poteau, deux diamètres inversés."),
    trouve_erreur_fiche(42, "Extrait d'une nomenclature d'armatures.", "NOMENCLATURE · POUTRE P4",
                        [("Repère 1", "3 HA20 — L = 5,60 m"), ("Repère 2", "2 HA14 — L = 5,60 m"),
                         ("Repère 2", "28 HA8 — cadres"), ("Repère 4", "6 HA10 — épingles"), ("Total", "4 repères")], 2, "Repère 3",
                        "Lis la **colonne de gauche**, ligne par ligne, sans regarder le reste.",
                        "Un **repère** apparaît / deux fois.", "Deux lignes différentes portent le même numéro de repère.",
                        "Un repère, un façonnage", "Le repère est le lien entre le plan, l'atelier et le chantier. En double, le ferrailleur **ne sait plus** quelle barre façonner, et le contrôle devient impossible.",
                        "Chaque ligne reçoit un repère unique, dans l'ordre.",
                        "une nomenclature, un numéro en double."),
    trouve_erreur_fiche(43, "Récapitulatif de ferraillage d'une poutre.", "RÉCAP. · POUTRE P4",
                        [("3 HA20", "L = 5,60 m → 41,5 kg"), ("2 HA14", "L = 5,60 m → 13,5 kg"),
                         ("28 HA8", "cadres → 15,0 kg"), ("6 HA10", "épingles → 5,0 kg"), ("Total", "35,0 kg")], 4, "75,0 kg",
                        "Additionne toi-même la colonne de droite, puis regarde la dernière ligne.",
                        "Le **total** ne / correspond pas.", "La somme des lignes dépasse largement le total annoncé.",
                        "Le total sert à commander l'acier", "C'est lui qui part au fournisseur et qui sert au métré. Un total faux, c'est un **chantier à l'arrêt** ou de l'acier payé en trop.",
                        "Le total se recalcule automatiquement à partir des lignes.",
                        "un récapitulatif, un total qui ne tombe pas juste."),
]
